# Generated by Django 6.0.2 on 2026-02-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('ANALYSTE_N1', 'Analyste Niveau 1'), ('ANALYSTE_N2', 'Analyste Niveau 2'), ('manager', 'Manager SOC')], default='ANALYSTE_N1', max_length=20),
        ),
    ]
