# Generated by Django 6.0.2 on 2026-02-10 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_incident', models.CharField(max_length=100)),
                ('severite', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4')], max_length=10)),
                ('statut', models.CharField(choices=[('Nouveau', 'Nouveau'), ('En cours', 'En cours'), ('Résolu', 'Résolu'), ('Fermé', 'Fermé')], default='Nouveau', max_length=20)),
                ('date_occurrence', models.DateTimeField()),
                ('date_detection', models.DateTimeField()),
                ('date_cloture', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('analyste_assigne', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
