# Generated by Django 6.0.2 on 2026-02-23 12:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id_incident', models.AutoField(primary_key=True, serialize=False)),
                ('incident_id_formatted', models.CharField(blank=True, help_text='Format: Date_Now + Nombre', max_length=100, null=True)),
                ('titre', models.CharField(blank=True, max_length=255, null=True)),
                ('date_detection', models.DateTimeField(default=django.utils.timezone.now)),
                ('insiter_typo', models.CharField(blank=True, choices=[('Mineur', 'Mineur'), ('Majeur', 'Majeur')], default='Mineur', max_length=10, null=True)),
                ('severity_level', models.CharField(blank=True, choices=[('High', 'High'), ('Low', 'Low'), ('Medium', 'Medium'), ('Critical', 'Critical')], default='Low', max_length=10, null=True)),
                ('category', models.CharField(blank=True, choices=[('Application', 'Application'), ('Web', 'Web'), ('Email', 'Email'), ('Authentification', 'Authentification')], default='Application', max_length=50, null=True)),
                ('plant_name', models.CharField(blank=True, choices=[('Site', 'Site'), ('COFTN', 'COFTN'), ('COFFR', 'COFFR')], default='Site', max_length=20, null=True)),
                ('raised_by', models.CharField(blank=True, max_length=100, null=True)),
                ('host_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user_name_pc', models.CharField(blank=True, max_length=100, null=True)),
                ('host_state', models.CharField(blank=True, choices=[('Blocked', 'Blocked'), ('Not Blocked', 'Not Blocked')], default='Not Blocked', max_length=15, null=True)),
                ('description_investigation', models.TextField(blank=True, null=True)),
                ('remediation_destination', models.CharField(blank=True, max_length=255, null=True)),
                ('first_event', models.DateTimeField(blank=True, null=True)),
                ('ticket_relise', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, null=True)),
                ('escalation', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, null=True)),
                ('incident_status', models.CharField(blank=True, choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], default='Open', max_length=20, null=True)),
                ('false_position', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, null=True)),
                ('impact_on_cofi_cob', models.TextField(blank=True, null=True)),
                ('help_desk_ticket_nb', models.CharField(blank=True, max_length=50, null=True)),
                ('date_target', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_of_closed_incident', models.DateTimeField(blank=True, null=True)),
                ('acknowledge_time', models.DateTimeField(blank=True, null=True)),
                ('user_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur associé')),
            ],
        ),
    ]
