# Generated by Django 6.0.2 on 2026-02-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='category',
            field=models.CharField(blank=True, choices=[('Application', 'Application'), ('Web', 'Web'), ('Email', 'Email'), ('Authentification', 'Authentification')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='escalation',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='false_position',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='host_state',
            field=models.CharField(blank=True, choices=[('Blocked', 'Blocked'), ('Not Blocked', 'Not Blocked')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='insiter_typo',
            field=models.CharField(blank=True, choices=[('Mineur', 'Mineur'), ('Majeur', 'Majeur')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='plant_name',
            field=models.CharField(blank=True, choices=[('Site', 'Site'), ('COFTN', 'COFTN'), ('COFFR', 'COFFR')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='severity_level',
            field=models.CharField(blank=True, choices=[('High', 'High'), ('Low', 'Low'), ('Medium', 'Medium'), ('Critical', 'Critical')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='ticket_relise',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
    ]
