# Generated by Django 6.0.2 on 2026-04-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_alter_incident_category_alter_incident_escalation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='evidence_image',
            field=models.ImageField(blank=True, null=True, upload_to='incident_evidence/'),
        ),
    ]
